package test;

public enum Menu {

    BASIC_INFORMATION("mnu-200", null),
    BASIC_INFORMATION_INVENTORIES("mnu-210", BASIC_INFORMATION),
    BASIC_INFORMATION_OFFICES("mnu-220", BASIC_INFORMATION),
    BASIC_INFORMATION_GUILDS("mnu-230", BASIC_INFORMATION),
    BASIC_INFORMATION_PRODUCTHIERARCHY("mnu-240", BASIC_INFORMATION),
    BASIC_INFORMATION_PRODUCTS("mnu-250", BASIC_INFORMATION),
    BASIC_INFORMATION_TARIFF("mnu-260", BASIC_INFORMATION),
    BASIC_INFORMATION_PLAN("mnu-270", BASIC_INFORMATION),
    BASIC_INFORMATION_SALEDIVISION("mnu-280", BASIC_INFORMATION),
    BASIC_INFORMATION_COUNTRYDIVISION("mnu-290", BASIC_INFORMATION),
    BASIC_INFORMATION_PRODUCTHIERARCHY_COMPANY("mnu-241", BASIC_INFORMATION_PRODUCTHIERARCHY),
    BASIC_INFORMATION_PRODUCTHIERARCHY_BRAND("mnu-242", BASIC_INFORMATION_PRODUCTHIERARCHY),
    BASIC_INFORMATION_PRODUCTHIERARCHY_LINE("mnu-243", BASIC_INFORMATION_PRODUCTHIERARCHY),
    BASIC_INFORMATION_PRODUCTHIERARCHY_CLASS("mnu-244", BASIC_INFORMATION_PRODUCTHIERARCHY),
    BASIC_INFORMATION_PRODUCTHIERARCHY_CATEGORY("mnu-245", BASIC_INFORMATION_PRODUCTHIERARCHY),
    BASIC_INFORMATION_PRODUCTHIERARCHY_GROUP("mnu-246", BASIC_INFORMATION_PRODUCTHIERARCHY),
    BASIC_INFORMATION_SALEDIVISION_INTERNATIONALTERRITORY("mnu-282", BASIC_INFORMATION_SALEDIVISION),
    BASIC_INFORMATION_SALEDIVISION_REGION("mnu-283", BASIC_INFORMATION_SALEDIVISION),
    BASIC_INFORMATION_SALEDIVISION_BRANCH("mnu-284", BASIC_INFORMATION_SALEDIVISION),
    BASIC_INFORMATION_SALEDIVISION_TERRITORY("mnu-285", BASIC_INFORMATION_SALEDIVISION),
    BASIC_INFORMATION_SALEDIVISION_AREA("mnu-286", BASIC_INFORMATION_SALEDIVISION),
    BASIC_INFORMATION_SALEDIVISION_DISTRICT("mnu-287", BASIC_INFORMATION_SALEDIVISION),
    BASIC_INFORMATION_COUNTRYDIVISION_COUNTRY("mnu-292", BASIC_INFORMATION_COUNTRYDIVISION),
    BASIC_INFORMATION_COUNTRYDIVISION_PROVINCE("mnu-293", BASIC_INFORMATION_COUNTRYDIVISION),
    BASIC_INFORMATION_COUNTRYDIVISION_CITY("mnu-294", BASIC_INFORMATION_COUNTRYDIVISION),
    BASIC_INFORMATION_COUNTRYDIVISION_CITYREGION("mnu-295", BASIC_INFORMATION_COUNTRYDIVISION)









    ;

    private String menuId;
    private Menu parentMenu;

    Menu(String menuId, Menu parentMenu){
        this.menuId = menuId;
        this.parentMenu = parentMenu;
    }

    public String getMenuId() {
        return menuId;
    }

    public Menu getParentMenu() {
        return parentMenu;
    }
}
